<?php
/**
 * Page Generator logic for Executive Acquisition theme
 */

/**
 * Register Customizer settings for the Page Generator
 */
function ea_generator_customize_register( $wp_customize ) {
    $wp_customize->add_section( 'ea_generator_section', array(
        'title'    => __( 'Page Generator / Setup', 'executive-acquisition' ),
        'priority' => 20,
        'description' => __( 'Use this tool to automatically generate or reset the core funnel pages. Warning: This will delete existing pages generated by this theme.', 'executive-acquisition' ),
    ) );

    $wp_customize->add_setting( 'ea_regenerate_trigger', array(
        'default'           => '',
        'sanitize_callback' => 'sanitize_text_field',
    ) );

    $wp_customize->add_control( new EA_Generator_Control( $wp_customize, 'ea_regenerate_trigger', array(
        'label'    => __( 'Regenerate Funnel Pages', 'executive-acquisition' ),
        'section'  => 'ea_generator_section',
        'settings' => 'ea_regenerate_trigger',
    ) ) );
}
add_action( 'customize_register', 'ea_generator_customize_register' );

/**
 * Custom Control for the Regenerate Button
 */
if ( class_exists( 'WP_Customize_Control' ) ) {
    class EA_Generator_Control extends WP_Customize_Control {
        public $type = 'ea_generator_button';

        public function render_content() {
            ?>
            <label>
                <span class="customize-control-title"><?php echo esc_html( $this->label ); ?></span>
                <button type="button" class="button button-primary ea-generator-btn" id="ea-regenerate-btn">
                    <?php _e( 'Generate / Reset Infrastructure', 'executive-acquisition' ); ?>
                </button>
                <span class="spinner" style="float:none; vertical-align: middle;"></span>
                <p class="description" style="margin-top: 10px;">
                    <?php _e( 'This will create: Home, About, Contact, Thank You, Briefing, Blog, ROI Proof, and Navigation Menus.', 'executive-acquisition' ); ?>
                </p>
            </label>
            <script type="text/javascript">
                jQuery(document).ready(function($) {
                    $('#ea-regenerate-btn').on('click', function(e) {
                        e.preventDefault();
                        if (!confirm('Are you sure? This will delete previously generated pages and menus.')) return;

                        var $btn = $(this);
                        var $spinner = $btn.next('.spinner');

                        $btn.attr('disabled', true);
                        $spinner.addClass('is-active');

                        $.post(ajaxurl, {
                            action: 'ea_generate_pages',
                            nonce: '<?php echo wp_create_nonce("ea_generator_nonce"); ?>'
                        }, function(response) {
                            $btn.attr('disabled', false);
                            $spinner.removeClass('is-active');
                            alert(response.data.message);
                            if (response.success) {
                                location.reload();
                            }
                        });
                    });
                });
            </script>
            <?php
        }
    }
}

/**
 * AJAX Handler for Page Generation
 */
function ea_ajax_generate_pages() {
    check_ajax_referer( 'ea_generator_nonce', 'nonce' );

    if ( ! current_user_can( 'manage_options' ) ) {
        wp_send_json_error( array( 'message' => __( 'Insufficient permissions.', 'executive-acquisition' ) ) );
    }

    // 1. Delete old pages
    $old_pages = get_posts( array(
        'post_type'  => 'page',
        'meta_key'   => '_ea_generated_page',
        'posts_per_page' => -1,
    ) );

    foreach ( $old_pages as $p ) {
        wp_delete_post( $p->ID, true );
    }

    // 2. Delete old menus
    $menus_to_delete = array('Executive Primary Menu', 'Executive Footer Menu');
    foreach($menus_to_delete as $m_name) {
        $old_menu = wp_get_nav_menu_object( $m_name );
        if ( $old_menu ) {
            wp_delete_nav_menu( $old_menu->term_id );
        }
    }

    // 3. Generate new pages
    $pages_to_create = array(
        'Home' => array(
            'template' => 'front-page.php',
            'content'  => '',
        ),
        'About Us' => array(
            'template' => 'template-about.php',
            'content'  => '<p>Since 2012, we have been the silent architects behind the leadership transitions of over 150 mid-market organizations. Our focus is absolute: measurable ROI through institutional authority.</p>',
        ),
        'Contact Us' => array(
            'template' => 'template-contact.php',
            'content'  => '',
        ),
        'Thank You' => array(
            'template' => 'template-thank-you.php',
            'content'  => '',
        ),
        'Executive Briefing' => array(
            'template' => 'template-briefing.php',
            'content'  => '',
        ),
        'Blog' => array(
            'template' => 'home.php',
            'content'  => '',
        ),
        'ROI Case Study' => array(
            'template' => 'template-case-study.php',
            'content'  => '[roi_callout value="+140%" label="Leadership Efficiency"]
                            [exec_quote author="VP Operations, Fortune 500"]This system eliminated our lead quality bottleneck within 90 days.[/exec_quote]
                            <h3>The Institutional Challenge</h3>
                            <p>Before implementing the method, the leadership team was trapped on the content hamster wheel, resulting in unqualified leads and wasted executive hours.</p>
                            <h3>The Engineered Solution</h3>
                            <p>By deploying the Authority Infrastructure, we replaced manual outreach with a surgical intent-based beacon.</p>',
        ),
        'Asset Library' => array(
            'template' => 'template-resources.php',
            'content'  => '',
        ),
        'Privacy Policy' => array(
            'template' => 'page.php',
            'content'  => '<p>We respect executive privacy. All data collected via this infrastructure is strictly confidential.</p>',
        ),
        'Terms of Service' => array(
            'template' => 'page.php',
            'content'  => '<p>Standard institutional terms of service for engagement diagnostic sessions.</p>',
        ),
    );

    // Create Menus
    $primary_menu_id = wp_create_nav_menu( 'Executive Primary Menu' );
    $footer_menu_id = wp_create_nav_menu( 'Executive Footer Menu' );

    $locations = get_theme_mod( 'nav_menu_locations' );
    $locations['primary'] = $primary_menu_id;
    $locations['footer'] = $footer_menu_id;
    set_theme_mod( 'nav_menu_locations', $locations );

    // 4. Generate Sample CPTs (if empty)
    if ( !get_posts(array('post_type' => 'testimonial')) ) {
        wp_insert_post( array(
            'post_title'   => 'Founder & CEO, Scale-Up Inc.',
            'post_content' => 'The Institutional Intent Method is the only acquisition strategy that respects the C-Suite attention span. We saw a 10x ROI in 4 months.',
            'post_status'  => 'publish',
            'post_type'    => 'testimonial',
        ) );
    }

    if ( !get_posts(array('post_type' => 'faq')) ) {
        wp_insert_post( array(
            'post_title'   => 'How do you handle data privacy for C-Suite leads?',
            'post_content' => 'We utilize encrypted infrastructure and enterprise-grade CRM integrations to ensure all executive data remains strictly confidential and compliant with institutional security standards.',
            'post_status'  => 'publish',
            'post_type'    => 'faq',
        ) );
    }

    // 5. Generate Sample Blog Post
    $sample_post_id = wp_insert_post( array(
        'post_title'   => 'The Institutional Intent Method: Scaling Leadership Beyond Referrals',
        'post_content' => '[roi_callout value="$2.4M" label="Retention Revenue Protected"]
                            <p>Most executive coaches rely on a referral-only model. While referrals provide high trust, they lack <strong>predictability</strong>.</p>
                            [exec_quote author="Strategic Growth Lead"]By implementing a surgical intent beacon, we were able to identify decision-makers months before they issued an RFP.[/exec_quote]
                            <p>In this insight, we break down the three pillars of institutional trust...</p>',
        'post_status'  => 'publish',
        'post_type'    => 'post',
    ) );

    $created_count = 0;
    foreach ( $pages_to_create as $title => $data ) {
        $page_id = wp_insert_post( array(
            'post_title'   => $title,
            'post_content' => $data['content'],
            'post_status'  => 'publish',
            'post_type'    => 'page',
        ) );

        if ( $page_id ) {
            update_post_meta( $page_id, '_wp_page_template', $data['template'] );
            update_post_meta( $page_id, '_ea_generated_page', '1' );

            // Add to Primary Menu
            $primary_titles = array('Home', 'About Us', 'ROI Case Study', 'Asset Library', 'Blog', 'Contact Us');
            if ( in_array($title, $primary_titles) ) {
                wp_update_nav_menu_item( $primary_menu_id, 0, array(
                    'menu-item-title'     => $title,
                    'menu-item-object'    => 'page',
                    'menu-item-object-id' => $page_id,
                    'menu-item-type'      => 'post_type',
                    'menu-item-status'    => 'publish',
                ) );
            }

            // Add to Footer Menu
            $footer_titles = array('Privacy Policy', 'Terms of Service');
            if ( in_array($title, $footer_titles) ) {
                wp_update_nav_menu_item( $footer_menu_id, 0, array(
                    'menu-item-title'     => $title,
                    'menu-item-object'    => 'page',
                    'menu-item-object-id' => $page_id,
                    'menu-item-type'      => 'post_type',
                    'menu-item-status'    => 'publish',
                ) );
            }

            // Set Reading Settings
            if ( $title === 'Home' ) {
                update_option( 'show_on_front', 'page' );
                update_option( 'page_on_front', $page_id );
            }
            if ( $title === 'Blog' ) {
                update_option( 'page_for_posts', $page_id );
            }
            $created_count++;
        }
    }

    wp_send_json_success( array( 'message' => sprintf( __( 'Success! %d pages, 2 menus, and authority CPT samples generated.', 'executive-acquisition' ), $created_count ) ) );
}
add_action( 'wp_ajax_ea_generate_pages', 'ea_ajax_generate_pages' );
